name: Ourhub api deploy

on:
  push:
    branches: [ "api-main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Build with Gradle Wrapper
      run: |
        cd api  # Acesse a pasta onde está o projeto
        ./gradlew build

    - name: Find JAR File
      run: |
        cd api  # Acesse a pasta onde está o projeto
        JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
        echo "Found JAR file: $JAR_FILE"
        echo "::set-output name=jar-path::$JAR_FILE" # Outputs the path for use in other jobs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH key for EC2 access
      run: |
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
        chmod 600 private_key.pem

    - name: Deploy JAR to EC2
      run: |
        JAR_PATH=${{ needs.build.outputs.jar-path }}
        # Use scp to copy the JAR file to EC2
        scp -i private_key.pem $JAR_PATH ubuntu@<EC2_PUBLIC_IP>:/home/ubuntu/
        # Connect to EC2 via SSH and run the JAR
        ssh -i private_key.pem ubuntu@<EC2_PUBLIC_IP> "java -jar /home/ubuntu/$(basename $JAR_PATH)"
